services:
  - type: web
    name: ghw-bot
    runtime: python
    pythonVersion: 3.12
    buildCommand: bash build.sh
    startCommand: python -u main.py
    envVars:
      - key: TELEGRAM_TOKEN
        scope: run
      - key: DATABASE_URL
        scope: run

